'use client';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { defaultGroup, dollarsToCents, recurringFloor, suggestBudget, templates, type Group, type Template } from '@/lib/budget-builder';
import type { BudgetView } from '@/lib/budget-planning';
import type { RecurringSchedule } from '@/lib/dashboard-insights';
import type { ReviewTransaction } from '@/lib/month-review';
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n/100);
const dollars=(n:number)=>(n/100).toFixed(2);
export default function BudgetBuilder({month,currentMonth,income,saving,budgets,recurring,transactions,busy,onClose,onApply,initialTemplate='balanced'}:{initialTemplate?:Template;month:string;currentMonth:string;income:number;saving:number;budgets:BudgetView[];recurring:RecurringSchedule[];transactions:ReviewTransaction[];busy:boolean;onClose:()=>void;onApply:(payload:Record<string,unknown>)=>Promise<boolean>}) {
  const [step,setStep]=useState(1);
  const [template,setTemplate]=useState<Template>(initialTemplate);
  const [incomeText,setIncomeText]=useState(dollars(income));
  const [savingText,setSavingText]=useState(dollars(saving));
  const [localError,setLocalError]=useState('');
  const [ack,setAck]=useState(false);
  const [success,setSuccess]=useState(false);
  const [floors]=useState(()=>recurringFloor(month,currentMonth,recurring,transactions));
  const [rows,setRows]=useState(()=>budgets.map(b=>({category:b.category,group:defaultGroup(b.category),text:dollars(b.base),fixed:dollars(floors.categories[b.category]??0)})));
  const [savingFixed,setSavingFixed]=useState(dollars(floors.saving??0));
  const incomeCents=dollarsToCents(incomeText);
  const savingCents=dollarsToCents(savingText);
  const parsed=rows.map(r=>({...r,amount:dollarsToCents(r.text),fixedAmount:dollarsToCents(r.fixed)}));
  const valid=incomeCents!==null&&savingCents!==null&&parsed.every(r=>r.amount!==null&&r.fixedAmount!==null);
  const assigned=parsed.reduce((n,r)=>n+(r.amount??0),savingCents??0);
  const remaining=(incomeCents??0)-assigned;
  const fixedTotal=parsed.reduce((n,r)=>n+(r.fixedAmount??0),dollarsToCents(savingFixed)??0);
  const belowFixed=parsed.some(r=>(r.amount??0)<(r.fixedAmount??0)) || (savingCents??0)<(dollarsToCents(savingFixed)??0);
  function generate() {
    if(!rows.length){setLocalError('Add a budget category before using the builder.');return;}
    if(incomeCents===null||parsed.some(r=>r.fixedAmount===null||r.amount===null)||dollarsToCents(savingFixed)===null){setLocalError('Enter amounts from $0 to $1,000,000 with up to two decimal places.');return;}
    const result=suggestBudget(incomeCents,template,parsed.map(r=>({category:r.category,group:r.group,amount:r.amount!,fixed:r.fixedAmount!})),dollarsToCents(savingFixed)!);
    setRows(rows.map((r,i)=>({...r,text:dollars(result.rows[i].amount)})));
    setSavingText(dollars(template==='custom'?Math.max(saving,dollarsToCents(savingFixed)!):result.saving));
    setLocalError('');setStep(2);setAck(false);
  }
  return <Dialog open onOpenChange={()=>{if(!busy)onClose()}}><DialogContent className="builder-dialog" showCloseButton={!busy}><DialogHeader><DialogTitle>{success?'Your budget is ready':'Budget Builder'}</DialogTitle><DialogDescription>{success?`Your plan starts in ${month}.`:`Plan ${month} with editable starting points based on your take-home income.`}</DialogDescription></DialogHeader>
    {success?<div className="form"><p>Your category limits and savings reserve have been saved. Record your actual saving and investing contributions separately, and link those entries to goals to track progress.</p><Button onClick={onClose}>Back to my budget</Button></div>:<div className="form">
    <ol className="builder-steps" aria-label="Budget setup progress">{['Choose a starting point','Adjust your plan','Review & apply'].map((label,i)=><li key={label} aria-current={step===i+1?'step':undefined}>{i+1}. {label}</li>)}</ol>
    {step===1&&<><label>Monthly take-home income ($)<Input type="number" min="0" max="1000000" step="0.01" value={incomeText} onChange={e=>setIncomeText(e.target.value)}/></label><p className="panel-sub">Use income after taxes. Cash carry-forward and category rollover are separate from this plan.</p><div className="builder-templates">{templates.map(t=><button type="button" aria-pressed={template===t.id} key={t.id} onClick={()=>setTemplate(t.id)}><strong>{t.name}</strong><span>{t.description}</span></button>)}</div><p className="panel-sub">Percentages are starting points. Higher commitments reduce flexible spending first, then extra saving. Adjust the result to fit your costs. Unrecognized categories start under wants; you can change their group below.</p><h3>Confirm your monthly commitments</h3><p className="panel-sub">Includes recorded recurring payments and scheduled payments for this month. Add missing bills here. These amounts are included within each category, not added twice.</p><div className="builder-rows">{rows.map((r,i)=><div className="builder-edit-row" key={r.category}><label>{r.category}<select aria-label={`${r.category} group`} value={r.group} onChange={e=>setRows(rows.map((v,j)=>j===i?{...v,group:e.target.value as Group}:v))}><option value="needs">Needs</option><option value="wants">Wants</option><option value="future">Saving / investing</option></select></label><label>Committed ($)<Input type="number" min="0" max="1000000" step="0.01" aria-label={`${r.category} commitment dollars`} value={r.fixed} onChange={e=>setRows(rows.map((v,j)=>j===i?{...v,fixed:e.target.value}:v))}/></label></div>)}</div><label>Committed saving ($)<Input type="number" min="0" step="0.01" value={savingFixed} onChange={e=>setSavingFixed(e.target.value)}/></label><Button onClick={generate}>Build my starting plan</Button></>}
    {step>=2&&<><div className="builder-summary" aria-live="polite"><div><span>Take-home income</span><strong>{money(incomeCents??0)}</strong></div><div><span>Assigned</span><strong>{money(assigned)}</strong></div><div className={remaining<0?'builder-warning':''}><span>{remaining<0?'Over income':'Left to assign'}</span><strong>{money(Math.abs(remaining))}</strong></div></div>{incomeCents===0&&<p className="builder-warning">No income is planned. Any allocation will need another funding source.</p>}{incomeCents!==null&&incomeCents>0&&<p className="panel-sub">Your commitments use {Math.round(fixedTotal/incomeCents*100)}% of your take-home income.</p>}{remaining<0&&<p className="builder-warning">This plan is {money(-remaining)} over your income. Reduce amounts or review your income before applying.</p>}{belowFixed&&<p className="builder-warning">Some allocations are below your entered commitments. Review whether those payments can be covered.</p>}
    {step===2?<><h3>Make it yours</h3><p className="panel-sub">Amounts include your commitments. Extra saving starts in the savings reserve; move it to Investing if you prefer. Put debt payments in the appropriate expense category.</p>{rows.map((r,i)=><div className="builder-edit-row" key={r.category}><label htmlFor={`builder-amount-${i}`}>{r.category}<small>{r.group} · {money(parsed[i].fixedAmount??0)} committed</small></label><Input id={`builder-amount-${i}`} aria-label={`${r.category} budget dollars`} type="number" min="0" max="1000000" step="0.01" value={r.text} onChange={e=>{setRows(rows.map((v,j)=>j===i?{...v,text:e.target.value}:v));setAck(false)}}/></div>)}<label>Savings reserve ($)<Input type="number" min="0" max="1000000" step="0.01" value={savingText} onChange={e=>{setSavingText(e.target.value);setAck(false)}}/></label><p className="panel-sub">This reserves part of your plan for savings. It does not record a contribution or change goal progress. Investing is already included in its category.</p></>:<><h3>Changes for {month} onward</h3><p className="panel-sub">Replaces the category base limits below from this month until their next saved change. Existing rollover modes stay in place, so actual allowances may differ. Earlier months and future saved changes stay intact. Planned income and the savings reserve follow the same effective-month behavior.</p><div className="builder-review"><div><strong>Category</strong><strong>Current base → New base</strong></div>{parsed.map(r=><div key={r.category}><span>{r.category}</span><span>{money(budgets.find(b=>b.category===r.category)?.base??0)} → {money(r.amount??0)}</span></div>)}<div><span>Planned income</span><span>{money(income)} → {money(incomeCents??0)}</span></div><div><span>Savings reserve</span><span>{money(saving)} → {money(savingCents??0)}</span></div></div><p className="panel-sub">A $0 category keeps the app’s existing “No limit set” behavior. Transactions, recurring schedules, and goals are unchanged.</p><label className="builder-ack"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/> I reviewed these replacements{remaining<0||belowFixed?' and the funding warnings':''}.</label></>}
    {!valid&&<p role="alert">Enter valid amounts from $0 to $1,000,000 with up to two decimal places.</p>}
    <div className="builder-actions"><Button variant="outline" disabled={busy} onClick={()=>{setStep(step-1);setLocalError('')}}>Back</Button>{step===2?<Button disabled={!valid} onClick={()=>{setStep(3);setAck(false)}}>Review changes</Button>:<Button disabled={!valid||!ack||busy} onClick={async()=>{setLocalError('');if(await onApply({action:'budgetBuilder',month,income:incomeCents,saving:savingCents,rows:parsed.map(r=>({category:r.category,amount:r.amount}))}))setSuccess(true);else setLocalError('Could not apply the budget. Your draft is still here; please try again.')}}>{busy?'Applying…':'Apply budget'}</Button>}</div></>}
    {localError&&<p className="builder-warning" role="alert">{localError}</p>}</div>}
  </DialogContent></Dialog>;
}
