'use client';
import { useEffect,useMemo,useState } from 'react';
import { LayoutDashboard,ArrowLeftRight,ChartNoAxesCombined,Target,Wallet,Plus,Search,Trash2,Pencil,TrendingUp,Download,ChevronLeft,ChevronRight,X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogFooter } from '@/components/ui/dialog';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { Progress } from '@/components/ui/progress';
import { PieChart,Pie,Cell,ResponsiveContainer,Tooltip } from 'recharts';
import { getSupabase } from './supabase-client';

type Tx={id:number;date:string;name:string;amount:number;category:string;type:string};
type Budget={category:string;amount:number};type Goal={id:number;name:string;type:string;target:number;current:number};
type Data={transactions:Tx[];budgets:Budget[];goals:Goal[];demo:boolean;monthlyIncome:number};
const categories=['Housing','Utilities','Food','Transportation','Shopping','Entertainment','Subscriptions','Miscellaneous'];
const palette=['#166761','#357e98','#d1973d','#8e68a8','#4e8b70','#d16e63','#7694ad','#ac876e'];
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n/100);
const monthName=(m:string)=>new Date(`${m}-15T12:00:00`).toLocaleDateString('en-US',{month:'long',year:'numeric'});
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const currentMonth=()=>today().slice(0,7);
const csvEscape=(s:string)=>`"${s.replaceAll('"','""')}"`;
export default function DashboardClient({displayName,accessToken,onSignOut}:{displayName:string;accessToken?:string;onSignOut?:()=>void}){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [tab,setTab]=useState('Overview'),[month,setMonth]=useState(currentMonth());
 const [txOpen,setTxOpen]=useState(false),[editTx,setEditTx]=useState<Tx|null>(null),[txForm,setTxForm]=useState({name:'',amount:'',date:today(),category:'Food',type:'expense'});
 const [goalOpen,setGoalOpen]=useState(false),[editGoal,setEditGoal]=useState<Goal|null>(null),[goalForm,setGoalForm]=useState({name:'',type:'saving',target:'',current:''});
 const [budgetEdit,setBudgetEdit]=useState<string|null>(null),[budgetAmount,setBudgetAmount]=useState('');
 const [incomeEdit,setIncomeEdit]=useState(false),[incomeAmount,setIncomeAmount]=useState('');
 const [query,setQuery]=useState(''),[filter,setFilter]=useState('All');
 async function apiFetch(payload?:Record<string,unknown>){
  const headers:Record<string,string>={};
  if(accessToken){const {data:{session}}=await getSupabase().auth.getSession();if(!session)throw Error('Your session expired. Please sign in again.');headers.Authorization=`Bearer ${session.access_token}`;}
  if(payload)headers['Content-Type']='application/json';
  return fetch('/api/data',{method:payload?'POST':'GET',headers,body:payload?JSON.stringify(payload):undefined});
 }
 useEffect(()=>{apiFetch().then(async r=>{const x=await r.json() as Data & {error?:string};if(!r.ok)throw Error(x.error);setData(x)}).catch(e=>setError(e.message))},[accessToken]);
 useEffect(()=>{
  const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
  if(!context?.registerTool)return;
  const lifecycle=new AbortController();
  try{void Promise.resolve(context.registerTool({name:'start_transaction_entry',title:'Start transaction entry',description:'Open the transaction form so the user can record an expense, income, saving, or investing transfer.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:()=>{openTx();return {form:'open'}}},{signal:lifecycle.signal})).catch(()=>{});}catch{}
  return ()=>lifecycle.abort();
 },[]);

 async function save(payload:Record<string,unknown>){setBusy(true);setError('');try{const r=await apiFetch(payload);const x=await r.json() as Data & {error?:string};if(!r.ok)throw Error(x.error);setData(x);return true}catch(e){setError(e instanceof Error?e.message:'Could not save');return false}finally{setBusy(false)}}
 const monthly=useMemo(()=>data?.transactions.filter(t=>t.date.startsWith(month))??[],[data,month]);
 const income=monthly.filter(t=>t.type==='income').reduce((a,t)=>a+t.amount,0);
 const spent=monthly.filter(t=>t.type==='expense').reduce((a,t)=>a+t.amount,0);
 const saved=monthly.filter(t=>t.type==='saving').reduce((a,t)=>a+t.amount,0);
 const invested=monthly.filter(t=>t.type==='investing').reduce((a,t)=>a+t.amount,0);
 const budgetTotal=data?.budgets.reduce((a,b)=>a+b.amount,0)??0;
 const plannedIncome=data?.monthlyIncome??0;
 const plannedRemaining=plannedIncome-budgetTotal;
 const allocationPercent=plannedIncome?Math.min(100,Math.round(budgetTotal/plannedIncome*100)):0;
 const breakdown=categories.map((name,i)=>({name,value:monthly.filter(t=>t.type==='expense'&&t.category===name).reduce((a,t)=>a+t.amount,0),color:palette[i]})).filter(x=>x.value>0).sort((a,b)=>b.value-a.value);
 function changeMonth(n:number){const [y,m]=month.split('-').map(Number);const d=new Date(y,m-1+n,1);setMonth(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`)}
 function openTx(t?:Tx){setEditTx(t??null);setTxForm(t?{name:t.name,amount:(t.amount/100).toFixed(2),date:t.date,category:t.category,type:t.type}:{name:'',amount:'',date:today(),category:'Food',type:'expense'});setTxOpen(true)}
 function openIncome(){setEditTx(null);setTxForm({name:'Paycheck',amount:'',date:today(),category:'income',type:'income'});setTxOpen(true)}
 function openGoal(g?:Goal){setEditGoal(g??null);setGoalForm(g?{name:g.name,type:g.type,target:(g.target/100).toString(),current:(g.current/100).toString()}:{name:'',type:'saving',target:'',current:''});setGoalOpen(true)}
 function exportCsv(){if(!data)return;const rows=[['Date','Description','Type','Category','Amount'],...data.transactions.map(t=>[t.date,t.name,t.type,t.category,(t.amount/100).toFixed(2)])];const blob=new Blob([rows.map(row=>row.map(csvEscape).join(',')).join('\n')],{type:'text/csv'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='my-money-transactions.csv';a.click();URL.revokeObjectURL(url)}
 const visible=monthly.filter(t=>(filter==='All'||t.type===filter||t.category===filter)&&`${t.name} ${t.category}`.toLowerCase().includes(query.toLowerCase()));
 const initials=displayName.split(/[@\s]+/).filter(Boolean).slice(0,2).map(part=>part[0]?.toUpperCase()).join('') || 'ME';
 const nav=[['Overview',LayoutDashboard],['Transactions',ArrowLeftRight],['Budget',Wallet],['Goals',Target],['Analytics',ChartNoAxesCombined]] as const;
 return <div className="app-shell">
  <aside className="sidebar"><div className="brand"><div className="brand-icon"><TrendingUp size={22}/></div><span>my<span className="brand-light">money</span></span></div><div className="sidebar-label">WORKSPACE</div><nav aria-label="Main navigation">{nav.map(([name,Icon])=><button key={name} className={`nav-item ${tab===name?'active':''}`} onClick={()=>setTab(name)}><Icon size={19}/>{name}</button>)}</nav><div className="sidebar-foot"><div className="avatar">{initials}</div><div><strong className="user-name">{displayName}</strong><span>My budget</span></div>{onSignOut?<button className="sign-out" onClick={onSignOut}>Sign out</button>:<a className="sign-out" href="/signout-with-chatgpt?return_to=/" target="_top">Sign out</a>}</div></aside>
  <main className="main"><header className="topbar"><div className="mobile-brand"><span className="brand-icon"><TrendingUp size={18}/></span> mymoney</div><span className="breadcrumb">Your workspace <span>/</span> {tab}</span><div className="top-actions"><span className="private-pill">Private</span><div className="avatar small">{initials}</div></div></header>
   <div className="content"><div className="heading"><div><p className="eyebrow">PERSONAL FINANCE</p><h1>{tab==='Overview'?'Your money, at a glance':tab}</h1><p className="subhead">{tab==='Overview'?'See where your money goes and what’s left for the month.':tab==='Transactions'?'Every dollar in and out, in one place.':tab==='Budget'?'Set monthly limits and stay on top of spending.':tab==='Goals'?'Make room for saving and investing.':'Explore your spending patterns.'}</p></div><div className="heading-actions"><div className="month-control"><button aria-label="Previous month" onClick={()=>changeMonth(-1)}><ChevronLeft size={17}/></button><span>{monthName(month)}</span><button aria-label="Next month" onClick={()=>changeMonth(1)}><ChevronRight size={17}/></button></div>{(tab==='Overview'||tab==='Transactions')&&<><Button variant="outline" onClick={openIncome}><Plus size={17}/> Add paycheck</Button><Button onClick={()=>openTx()} className="primary-action"><Plus size={17}/> Add transaction</Button></>}</div></div>
    {data?.demo&&<div className="demo-banner"><div><strong>Sample data</strong><span> These numbers are examples. Explore the app, then remove the examples when you’re ready. Anything you add or edit stays.</span></div><Button variant="outline" disabled={busy} onClick={async()=>{if(confirm('Remove the sample transactions, budgets, and goals? Your own entries will stay.'))await save({action:'clearDemo'})}}>Start with my data</Button></div>}
    {error&&<div className="error" role="alert">{error}<button aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}
    {!data&&!error&&<div className="loading">Loading your budget…</div>}
    {data&&tab==='Overview'&&<><div className="stats-grid"><article className="stat-card featured"><span className="stat-label">Income this month</span><strong>{money(income)}</strong><span className="stat-note">Money coming in</span><div className="stat-deco">↗</div></article><article className="stat-card"><span className="stat-label">Spent this month</span><strong>{money(spent)}</strong><span className="stat-note">{income?`${Math.round(spent/income*100)}% of income`:'Record income to compare'}</span></article><article className="stat-card"><span className="stat-label">Saved + invested</span><strong>{money(saved+invested)}</strong><span className="stat-note">{money(saved)} saved · {money(invested)} invested</span></article><article className="stat-card"><span className="stat-label">Unallocated income</span><strong>{money(income-spent-saved-invested)}</strong><span className="stat-note">Income less spending and transfers</span></article></div>
     <div className="two-col"><section className="panel"><div className="panel-title"><div><h2>Monthly budget</h2><p>Spending against your category limits</p></div><button className="text-button" onClick={()=>setTab('Budget')}>View budget →</button></div><div className="budget-summary"><strong>{money(spent)}</strong><span>of {money(budgetTotal)} planned</span></div><Progress value={budgetTotal?Math.min(100,spent/budgetTotal*100):0} className="large-progress"/><div className="budget-bottom"><span>{money(Math.max(0,budgetTotal-spent))} remaining</span><span>{budgetTotal?Math.round(spent/budgetTotal*100):0}% used</span></div><div className="mini-budgets">{data.budgets.slice(0,4).map(b=>{const used=breakdown.find(x=>x.name===b.category)?.value??0;return <div key={b.category}><span>{b.category}</span><div className="thin-track"><i style={{width:`${b.amount?Math.min(100,used/b.amount*100):0}%`}}/></div><span>{money(used)} / {money(b.amount)}</span></div>})}</div></section>
     <section className="panel"><div className="panel-title"><div><h2>Where it went</h2><p>Spending by category this month</p></div><button className="text-button" onClick={()=>setTab('Analytics')}>Analytics →</button></div>{breakdown.length?<div className="donut-layout"><div className="donut"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={breakdown} dataKey="value" innerRadius="70%" outerRadius="95%" paddingAngle={3} stroke="none">{breakdown.map(x=><Cell key={x.name} fill={x.color}/>)}</Pie><Tooltip formatter={(value)=>money(Number(value))}/></PieChart></ResponsiveContainer><div className="donut-center"><small>Total spent</small><strong>{money(spent)}</strong></div></div><div className="legend">{breakdown.slice(0,6).map(x=><div key={x.name}><span className="legend-name"><i style={{background:x.color}}/>{x.name}</span><strong>{money(x.value)}</strong></div>)}</div></div>:<p className="empty">No expenses recorded for this month.</p>}</section></div>
     <div className="two-col lower"><section className="panel"><div className="panel-title"><div><h2>Recent activity</h2><p>Your latest transactions this month</p></div><button className="text-button" onClick={()=>setTab('Transactions')}>View all →</button></div>{monthly.slice(0,5).map(t=><TransactionRow key={t.id} t={t} onClick={()=>openTx(t)}/>)}{!monthly.length&&<p className="empty">Nothing recorded yet. Add your first transaction.</p>}</section><section className="panel"><div className="panel-title"><div><h2>Goals in progress</h2><p>Track what you set aside</p></div><button className="text-button" onClick={()=>setTab('Goals')}>View goals →</button></div>{data.goals.map(g=><div className="goal-preview" key={g.id}><div><span>{g.type==='investing'?'↗':'✦'}</span><strong>{g.name}</strong><small>{money(g.current)} / {money(g.target)}</small></div><Progress value={Math.min(100,g.current/g.target*100)}/></div>)}{!data.goals.length&&<p className="empty">Add a goal to track your progress.</p>}</section></div></>}
    {data&&tab==='Transactions'&&<section className="panel full-panel"><div className="table-tools"><div className="search"><Search size={18}/><Input aria-label="Search transactions" placeholder="Search transactions" value={query} onChange={e=>setQuery(e.target.value)}/></div><Select value={filter} onValueChange={v=>setFilter(v??'All')}><SelectTrigger className="filter-select"><SelectValue placeholder="All categories"/></SelectTrigger><SelectContent>{['All','income','expense','saving','investing',...categories].map(x=><SelectItem key={x} value={x}>{x==='All'?'All transactions':x[0].toUpperCase()+x.slice(1)}</SelectItem>)}</SelectContent></Select><Button variant="outline" onClick={exportCsv}><Download size={16}/> Export CSV</Button></div><div className="table-header"><span>TRANSACTION</span><span>CATEGORY</span><span>DATE</span><span>AMOUNT</span><span></span></div>{visible.map(t=><div className="table-row" key={t.id}><div className="transaction-name"><span className={`tx-icon ${t.type}`}>{t.type==='income'?'↙':t.type==='investing'?'↗':t.type==='saving'?'✦':'↗'}</span><strong>{t.name}</strong></div><span className="category-pill">{t.category}</span><span>{new Date(`${t.date}T12:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}</span><strong className={t.type==='income'?'positive':''}>{t.type==='income'?'+':'−'}{money(t.amount)}</strong><div className="row-actions"><button aria-label={`Edit ${t.name}`} onClick={()=>openTx(t)}><Pencil size={16}/></button><button aria-label={`Delete ${t.name}`} onClick={()=>{if(confirm(`Delete ${t.name}?`))void save({action:'deleteTransaction',id:t.id})}}><Trash2 size={16}/></button></div></div>)}{!visible.length&&<p className="empty">No transactions match this view.</p>}</section>}
    {data&&tab==='Budget'&&<><div className={`allocation-hero ${plannedRemaining<0?'over':''}`}><div><span className="eyebrow">AVAILABLE TO ALLOCATE</span><strong>{plannedIncome?money(Math.abs(plannedRemaining)):'—'}</strong><p>{!plannedIncome?'Set your planned monthly take-home income to start splitting it across categories.':plannedRemaining<0?`You’ve assigned ${money(Math.abs(plannedRemaining))} more than your planned income.`:`This is the amount you still have left to divide across your budget.`}</p></div><div className="allocation-hero-side"><div><span>Planned income</span><b>{money(plannedIncome)}</b></div><div><span>Already assigned</span><b>{money(budgetTotal)}</b></div><div><span>Allocated</span><b>{allocationPercent}%</b></div></div></div><div className="income-plan"><div><span className="eyebrow">MONTHLY PLAN</span><h2>Plan your income</h2><p>Set your expected take-home, then split it across categories. Record paychecks separately to compare your plan with what you actually received.</p></div><div className="income-plan-value"><strong>{money(plannedIncome)}</strong><div className="income-plan-actions"><Button variant="outline" onClick={openIncome}>Add paycheck</Button><Button variant="outline" onClick={()=>{setIncomeAmount(plannedIncome?(plannedIncome/100).toString():'');setIncomeEdit(true)}}>{plannedIncome?'Edit plan':'Set plan'}</Button></div></div></div><div className="allocation-grid secondary-allocation"><article><span>Actual take-home this month</span><strong>{money(income)}</strong><small>{income?`${monthly.filter(t=>t.type==='income').length} income entr${monthly.filter(t=>t.type==='income').length===1?'y':'ies'} recorded`:'Add a paycheck when you get paid'}</small></article><article><span>Budget assigned</span><strong>{money(budgetTotal)}</strong><small>{plannedIncome?`${allocationPercent}% of planned income`:'Set income to compare'}</small></article><article><span>Spent so far</span><strong>{money(spent)}</strong><small>{budgetTotal?`${Math.round(spent/budgetTotal*100)}% of assigned budget used`:'Set category limits to compare'}</small></article></div><div className="budget-list">{categories.map((c,i)=>{const b=data.budgets.find(x=>x.category===c);const used=breakdown.find(x=>x.name===c)?.value??0;return <div className="budget-row" key={c}><div className="budget-color" style={{background:palette[i]}}/><div className="budget-details"><div><strong>{c}</strong><span>{money(used)} of {money(b?.amount??0)}</span></div><Progress value={b?.amount?Math.min(100,used/b.amount*100):0}/><small>{b?.amount?used>b.amount?`${money(used-b.amount)} over budget`:`${money(b.amount-used)} remaining`:'No limit set'}{income&&b?.amount?` · ${Math.round(b.amount/income*100)}% of actual take-home`:plannedIncome&&b?.amount?` · ${Math.round(b.amount/plannedIncome*100)}% of planned income`:''}</small></div><Button variant="outline" onClick={()=>{setBudgetEdit(c);setBudgetAmount(b?(b.amount/100).toString():'')}}>Edit limit</Button></div>})}</div></>}
    {data&&tab==='Goals'&&<><div className="section-action"><p>Track balances you enter manually. Savings and investments are separate from spending.</p><Button onClick={()=>openGoal()} className="primary-action"><Plus size={17}/> Add goal</Button></div><div className="goals-grid">{data.goals.map(g=><article className="goal-card" key={g.id}><div className="goal-card-head"><div className="goal-badge">{g.type==='investing'?'↗':'✦'}</div><div className="row-actions"><button aria-label={`Edit ${g.name}`} onClick={()=>openGoal(g)}><Pencil size={17}/></button><button aria-label={`Delete ${g.name}`} onClick={()=>{if(confirm(`Delete ${g.name}?`))void save({action:'deleteGoal',id:g.id})}}><Trash2 size={17}/></button></div></div><span className="goal-type">{g.type==='investing'?'INVESTING':'SAVING'}</span><h2>{g.name}</h2><strong>{money(g.current)}</strong><p>of {money(g.target)} goal</p><Progress value={Math.min(100,g.current/g.target*100)}/><small>{Math.round(g.current/g.target*100)}% complete</small></article>)}{!data.goals.length&&<div className="panel empty">No goals yet. Add one to start tracking savings or investments.</div>}</div></>}
    {data&&tab==='Analytics'&&<><div className="stats-grid three"><article className="stat-card"><span className="stat-label">Income</span><strong>{money(income)}</strong></article><article className="stat-card"><span className="stat-label">Spending</span><strong>{money(spent)}</strong></article><article className="stat-card"><span className="stat-label">Savings + investing rate</span><strong>{income?`${Math.round((saved+invested)/income*100)}%`:'—'}</strong><span className="stat-note">Based on recorded transfers</span></article></div><div className="two-col analytics-top"><section className="panel"><div className="panel-title"><div><h2>Spending mix</h2><p>Share of this month’s expenses by category</p></div></div>{breakdown.length?<div className="analytics-pie-layout"><div className="analytics-pie"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={breakdown} dataKey="value" nameKey="name" innerRadius="48%" outerRadius="88%" paddingAngle={2} stroke="none">{breakdown.map(x=><Cell key={x.name} fill={x.color}/>)}</Pie><Tooltip formatter={(value)=>money(Number(value))}/></PieChart></ResponsiveContainer><div className="donut-center"><small>Total spent</small><strong>{money(spent)}</strong></div></div><div className="analytics-legend">{breakdown.map(x=><div key={x.name}><span><i style={{background:x.color}}/>{x.name}</span><strong>{spent?Math.round(x.value/spent*100):0}%</strong></div>)}</div></div>:<p className="empty">No expenses recorded for this month.</p>}</section><section className="panel"><h2>Money flow</h2><p className="panel-sub">Where recorded income went</p><div className="flow-row"><span>Income</span><strong>{money(income)}</strong></div><div className="flow-row"><span>Spending</span><strong>− {money(spent)}</strong></div><div className="flow-row"><span>Saved</span><strong>− {money(saved)}</strong></div><div className="flow-row"><span>Invested</span><strong>− {money(invested)}</strong></div><div className="flow-row total"><span>Unallocated</span><strong>{money(income-spent-saved-invested)}</strong></div><p className="flow-note">Transfers count here only when entered as saving or investing transactions. Goal balances are tracked separately.</p></section></div></>}
   </div><nav className="mobile-nav" aria-label="Mobile navigation">{nav.map(([name,Icon])=><button key={name} className={tab===name?'active':''} onClick={()=>setTab(name)}><Icon size={20}/><span>{name}</span></button>)}</nav></main>
  <Dialog open={txOpen} onOpenChange={setTxOpen}><DialogContent><DialogHeader><DialogTitle>{editTx?'Edit transaction':'Add transaction'}</DialogTitle></DialogHeader><form className="form" onSubmit={async e=>{e.preventDefault();if(await save({action:'transaction',...txForm,id:editTx?.id}))setTxOpen(false)}}><label>Type<Select value={txForm.type} onValueChange={v=>setTxForm({...txForm,type:v??'expense',category:v==='expense'?'Food':v??'expense'})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{['expense','income','saving','investing'].map(x=><SelectItem key={x} value={x}>{x[0].toUpperCase()+x.slice(1)}</SelectItem>)}</SelectContent></Select></label><label>Description<Input required maxLength={100} value={txForm.name} onChange={e=>setTxForm({...txForm,name:e.target.value})} placeholder="e.g. Groceries"/></label><div className="form-pair"><label>Amount ($)<Input required type="number" min="0.01" step="0.01" value={txForm.amount} onChange={e=>setTxForm({...txForm,amount:e.target.value})} placeholder="0.00"/></label><label>Date<Input required type="date" value={txForm.date} onChange={e=>setTxForm({...txForm,date:e.target.value})}/></label></div>{txForm.type==='expense'&&<label>Category<Select value={txForm.category} onValueChange={v=>setTxForm({...txForm,category:v??'Food'})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{categories.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></label>}<DialogFooter><Button type="button" variant="outline" onClick={()=>setTxOpen(false)}>Cancel</Button><Button disabled={busy} type="submit">{busy?'Saving…':'Save transaction'}</Button></DialogFooter></form></DialogContent></Dialog>
  <Dialog open={incomeEdit} onOpenChange={setIncomeEdit}><DialogContent><DialogHeader><DialogTitle>Monthly income</DialogTitle></DialogHeader><form className="form" onSubmit={async e=>{e.preventDefault();if(await save({action:'monthlyIncome',amount:incomeAmount}))setIncomeEdit(false)}}><label>Expected monthly income ($)<Input autoFocus required type="number" min="0" step="0.01" value={incomeAmount} onChange={e=>setIncomeAmount(e.target.value)} placeholder="5000"/></label><p className="panel-sub">Use your expected take-home income for the month. This is used for planning and is separate from income transactions you record.</p><DialogFooter><Button type="button" variant="outline" onClick={()=>setIncomeEdit(false)}>Cancel</Button><Button disabled={busy} type="submit">Save income</Button></DialogFooter></form></DialogContent></Dialog>
  <Dialog open={budgetEdit!==null} onOpenChange={v=>{if(!v)setBudgetEdit(null)}}><DialogContent><DialogHeader><DialogTitle>{budgetEdit} monthly limit</DialogTitle></DialogHeader><form className="form" onSubmit={async e=>{e.preventDefault();if(await save({action:'budget',category:budgetEdit,amount:budgetAmount}))setBudgetEdit(null)}}><label>Monthly limit ($)<Input autoFocus required type="number" min="0" step="0.01" value={budgetAmount} onChange={e=>setBudgetAmount(e.target.value)}/></label><DialogFooter><Button type="button" variant="outline" onClick={()=>setBudgetEdit(null)}>Cancel</Button><Button disabled={busy} type="submit">Save limit</Button></DialogFooter></form></DialogContent></Dialog>
  <Dialog open={goalOpen} onOpenChange={setGoalOpen}><DialogContent><DialogHeader><DialogTitle>{editGoal?'Edit goal':'Add goal'}</DialogTitle></DialogHeader><form className="form" onSubmit={async e=>{e.preventDefault();if(await save({action:'goal',...goalForm,id:editGoal?.id}))setGoalOpen(false)}}><label>Goal name<Input required maxLength={100} value={goalForm.name} onChange={e=>setGoalForm({...goalForm,name:e.target.value})} placeholder="e.g. Emergency fund"/></label><label>Type<Select value={goalForm.type} onValueChange={v=>setGoalForm({...goalForm,type:v??'saving'})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="saving">Saving</SelectItem><SelectItem value="investing">Investing</SelectItem></SelectContent></Select></label><div className="form-pair"><label>Target ($)<Input required type="number" min="0.01" step="0.01" value={goalForm.target} onChange={e=>setGoalForm({...goalForm,target:e.target.value})}/></label><label>Current amount ($)<Input required type="number" min="0" step="0.01" value={goalForm.current} onChange={e=>setGoalForm({...goalForm,current:e.target.value})}/></label></div><DialogFooter><Button type="button" variant="outline" onClick={()=>setGoalOpen(false)}>Cancel</Button><Button disabled={busy} type="submit">Save goal</Button></DialogFooter></form></DialogContent></Dialog>
 </div>
}
function TransactionRow({t,onClick}:{t:Tx;onClick:()=>void}){return <button className="recent-row" onClick={onClick}><span className={`tx-icon ${t.type}`}>{t.type==='income'?'↙':t.type==='saving'?'✦':'↗'}</span><span><strong>{t.name}</strong><small>{t.category} · {new Date(`${t.date}T12:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric'})}</small></span><b className={t.type==='income'?'positive':''}>{t.type==='income'?'+':'−'}{money(t.amount)}</b></button>}
