-- Recurring income and expense rules.
create table public.recurring_items (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade default auth.uid(),
  name text not null check (length(name) between 1 and 100),
  amount integer not null check (amount > 0),
  category text not null,
  type text not null check (type in ('expense', 'income')),
  frequency text not null check (frequency in ('monthly')),
  day_of_month integer not null check (day_of_month between 1 and 31),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create index recurring_items_owner_idx on public.recurring_items(owner_id);

alter table public.recurring_items enable row level security;
revoke all on public.recurring_items from anon;
grant select, insert, update, delete on public.recurring_items to authenticated;
grant usage, select on sequence public.recurring_items_id_seq to authenticated;

create policy recurring_items_owner on public.recurring_items for all to authenticated
  using (owner_id = (select auth.uid())) with check (owner_id = (select auth.uid()));
