create table public.feedback (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade default auth.uid(),
  message text not null check (length(message) between 1 and 2000),
  created_at timestamptz not null default now()
);

create index feedback_owner_created_idx
  on public.feedback(owner_id, created_at desc);

alter table public.feedback enable row level security;
revoke all on public.feedback from anon;
grant insert on public.feedback to authenticated;
grant usage, select on sequence public.feedback_id_seq to authenticated;

create policy feedback_insert_own
  on public.feedback
  for insert
  to authenticated
  with check (owner_id = (select auth.uid()));
