-- Amounts are stored in cents. Every row belongs to an authenticated user.
create table public.transactions (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade default auth.uid(),
  date date not null,
  name text not null check (length(name) between 1 and 100),
  amount integer not null check (amount > 0),
  category text not null,
  type text not null check (type in ('expense', 'income', 'saving', 'investing')),
  demo boolean not null default false
);

create index transactions_owner_date_idx on public.transactions(owner_id, date desc, id desc);

create table public.budgets (
  owner_id uuid not null references auth.users(id) on delete cascade default auth.uid(),
  category text not null,
  amount integer not null check (amount >= 0),
  demo boolean not null default false,
  primary key (owner_id, category)
);

create table public.goals (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade default auth.uid(),
  name text not null check (length(name) between 1 and 100),
  type text not null check (type in ('saving', 'investing')),
  target integer not null check (target > 0),
  current integer not null check (current >= 0),
  demo boolean not null default false
);

create index goals_owner_idx on public.goals(owner_id);

create table public.settings (
  owner_id uuid not null references auth.users(id) on delete cascade default auth.uid(),
  key text not null,
  value text not null,
  primary key (owner_id, key)
);

alter table public.transactions enable row level security;
alter table public.budgets enable row level security;
alter table public.goals enable row level security;
alter table public.settings enable row level security;

-- Explicit grants plus policies: anonymous clients receive no table access.
revoke all on public.transactions, public.budgets, public.goals, public.settings from anon;
grant select, insert, update, delete on public.transactions, public.budgets, public.goals, public.settings to authenticated;
grant usage, select on sequence public.transactions_id_seq, public.goals_id_seq to authenticated;

create policy transactions_owner on public.transactions for all to authenticated
  using (owner_id = (select auth.uid())) with check (owner_id = (select auth.uid()));
create policy budgets_owner on public.budgets for all to authenticated
  using (owner_id = (select auth.uid())) with check (owner_id = (select auth.uid()));
create policy goals_owner on public.goals for all to authenticated
  using (owner_id = (select auth.uid())) with check (owner_id = (select auth.uid()));
create policy settings_owner on public.settings for all to authenticated
  using (owner_id = (select auth.uid())) with check (owner_id = (select auth.uid()));
